public class CallRest {
public static String getAccessToken(){
        //definimos los parametros que usaremos para autenticarnos
        String accessEndpoint='https://login.salesforce.com/services/oauth2/token';
        String username = 'usuariorest@cloudco.com.mx.demo'; 
        String password = 'Demo20192019';
        String securityToken= 'z9EraU98TZyhwh9KMCsYBMTPJ';
        String clientKey = '3MVG9IHf89I1t8hrJIoUMzPBE_4mIAYWOO__KNAmKMsSrGVP930AxnWcaSFaxzEt2jSaNC3PphfGV9gOUNIrx';
        String clientSecret = '106A37F28B6143FB16D4C6C60FCC5547E55B5466A4EC95A490D3BB98F1C7A9C1';
        String Access_Token = '';
        }